Add some info about spatial instance
salute-developers/spatial pull request #3
Opened 2023-02-02 19:57 UTC by SeanSilke

2023-02-03 07:52 UTC, KateKate commented on README.md
> + Например фокусирование на определенной секции на маунт компонента будет выглядеть так
```suggestion
 Например, фокусирование на определенной секции на маунт компонента будет выглядеть так.
```

2023-02-03 07:52 UTC, KateKate commented on README.md
> +У инстанса SpatialNavigation есть ряд методов для упрощения некоторых сценариев
```suggestion
У инстанса SpatialNavigation есть ряд методов для упрощения некоторых сценариев:
```

2023-02-03 07:53 UTC, KateKate commented on README.md
> +        () => spatnavInstance.focus('@suggest');
```suggestion
        spatnavInstance.focus('@suggest');
```

2023-02-03 07:54 UTC, KateKate commented on README.md
> +        () => spatnavInstance.focus('@suggest');
а зачем `@`?

2023-02-03 07:54 UTC, KateKate commented on README.md
> +    <Suggest>
```suggestion
    <Suggest {...sectionProps}>
```

2023-02-03 08:06 UTC, arsenykruglikov commented on README.md
> +        () => spatnavInstance.focus('@suggest');
В spatnav 3 больше не надо @

2023-02-04 14:01 UTC, arsenykruglikov requested changes

2023-02-04 14:01 UTC, arsenykruglikov commented on README.md
> + - Фокусирование а указанной секции
- Фокусирование указанной секции

2023-02-06 09:45 UTC, KateKate approved these changes

2023-02-06 12:10 UTC, arsenykruglikov approved these changes

2023-02-07 11:35 UTC, merged